CREATE TABLE IF NOT EXISTS `bon_karyawan` (
  `FAKTUR` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `TANGGAL` datetime DEFAULT NULL,
  `LOKASI` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JENIS` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `KODE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `NAMA` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `KODE_REK` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_REK` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `AWAL_BON` decimal(15,0) DEFAULT '0',
  `NOMINAL` decimal(15,0) DEFAULT '0',
  `AKHIR_BON` decimal(15,0) DEFAULT '0',
  `KETERANGAN` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_USER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_KOMPUTER` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `sync_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`FAKTUR`),
  UNIQUE KEY `uq_sync_id_bon_karyawan` (`sync_id`),
  KEY `Bon_karyawan_ID_USER` (`ID_USER`),
  KEY `Bon_karyawan_Nama` (`NAMA`),
  KEY `idx_kode_tanggal_jenis_bon` (`KODE`,`TANGGAL`,`JENIS`),
  KEY `idx_tanggal_bon` (`TANGGAL`),
  KEY `idx_tanggal_jenis_bon` (`TANGGAL`,`JENIS`),
  KEY `idx_kode_tanggal_bon` (`KODE`,`TANGGAL`),
  KEY `idx_kode_jenis_tanggal_bon` (`KODE`,`JENIS`,`TANGGAL`),
  KEY `idx_faktur_bon` (`FAKTUR`),
  KEY `idx_jenis_bon` (`JENIS`),
  KEY `idx_kode_jenis_bon` (`KODE`,`JENIS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
