CREATE TABLE IF NOT EXISTS `gaji_karyawan` (
  `NOMOR` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `BULAN` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TANGGAL` datetime DEFAULT NULL,
  `TANGGALAWAL` datetime DEFAULT NULL,
  `TANGGALAKHIR` datetime DEFAULT NULL,
  `KODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `NAMA` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `POKOK` decimal(15,0) DEFAULT '0',
  `OMSET_JUAL` decimal(20,0) DEFAULT '0',
  `KOMISI_JUAL` decimal(10,0) DEFAULT '0',
  `SUPIR` int(11) DEFAULT '0',
  `SUPIR_RP` decimal(10,0) DEFAULT '0',
  `HELPER` int(11) DEFAULT '0',
  `HELPER_RP` decimal(10,0) DEFAULT '0',
  `LEMBUR` decimal(10,0) DEFAULT '0',
  `LEMBUR_RP` decimal(10,0) DEFAULT '0',
  `TUNJANGAN` decimal(10,0) DEFAULT '0',
  `TRANSP` decimal(10,0) DEFAULT '0',
  `TRANSPORT` decimal(10,0) DEFAULT '0',
  `UANG_MKN` decimal(10,0) DEFAULT '0',
  `UANG_MAKAN` decimal(10,0) DEFAULT '0',
  `SALDO_BON` decimal(10,0) DEFAULT '0',
  `POT_BON` decimal(10,0) DEFAULT '0',
  `ANGSURAN` decimal(10,0) DEFAULT '0',
  `NILAI_POTONGAN_ABSEN` decimal(10,0) DEFAULT '0',
  `ABSEN` decimal(10,0) DEFAULT '0',
  `ABSEN_RP` decimal(10,0) DEFAULT '0',
  `ABSEN_KHUSUS` decimal(10,0) DEFAULT '0',
  `ABSEN_KHUSUS_RP` decimal(10,0) DEFAULT '0',
  `TERLAMBAT` decimal(10,0) DEFAULT '0',
  `TERLAMBAT_RP` decimal(10,0) DEFAULT '0',
  `POT_LAIN` decimal(10,0) DEFAULT '0',
  `PENDAPATAN` decimal(15,0) DEFAULT '0',
  `POTONGAN` decimal(15,0) DEFAULT '0',
  `TERIMA` decimal(15,0) DEFAULT '0',
  `REKENING` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LOKASI` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_USER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_KOMPUTER` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `sync_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`NOMOR`),
  UNIQUE KEY `uq_sync_id_gaji_karyawan` (`sync_id`),
  KEY `idx_nomor_gaji` (`NOMOR`),
  KEY `idx_bulan_gaji` (`BULAN`),
  KEY `idx_kode_gaji` (`KODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
