CREATE TABLE IF NOT EXISTS `historybarang` (
  `NO` int(11) NOT NULL AUTO_INCREMENT,
  `FAKTUR` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TANGGAL` datetime DEFAULT NULL,
  `JENIS` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LOKASI` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_BARANG` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_BARANG` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `QTY` decimal(10,2) DEFAULT '0.00',
  `SATUAN` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ISI_SATUAN` int(11) DEFAULT '0',
  `TOTAL_QTY` decimal(10,2) DEFAULT '0.00',
  `TOTAL_RUPIAH` decimal(15,0) DEFAULT '0',
  `ID_USER` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_KOMPUTER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `sync_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`NO`),
  UNIQUE KEY `uq_sync_id_historybarang` (`sync_id`),
  KEY `HistoryBarang_ID_USER` (`ID_USER`),
  KEY `HistoryBarang_JENIS` (`JENIS`),
  KEY `HistoryBarang_TANGGAL` (`TANGGAL`),
  KEY `idx_faktur_history` (`FAKTUR`),
  KEY `idx_lokasi_jenis_barang_qty` (`LOKASI`,`JENIS`,`ID_BARANG`,`TOTAL_QTY`),
  KEY `idx_barang_jenis_tgl` (`ID_BARANG`,`JENIS`,`TANGGAL`),
  KEY `idx_barang_jenis_tgl_lokasi` (`ID_BARANG`,`JENIS`,`TANGGAL`,`LOKASI`),
  KEY `idx_barang_lokasi_tgl` (`ID_BARANG`,`LOKASI`,`TANGGAL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
