CREATE TABLE IF NOT EXISTS `hutang_detail` (
  `ID_BAYAR` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TANGGAL_BAYAR` datetime DEFAULT NULL,
  `LOKASI` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_BELI` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `KODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JENIS` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'BAYAR',
  `TANGGAL_BELI` datetime DEFAULT NULL,
  `TOTAL_HUTANG` decimal(15,0) DEFAULT '0',
  `DIBAYAR` decimal(15,0) DEFAULT '0',
  `RETUR` decimal(15,0) DEFAULT '0',
  `HUTANG` decimal(15,0) DEFAULT '0',
  `JATUH_TEMPO` datetime DEFAULT NULL,
  `PEMBAYARAN` decimal(15,0) DEFAULT '0',
  `STATUS` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_USER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_KOMPUTER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `sync_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  UNIQUE KEY `uq_sync_id_hutang_detail` (`sync_id`),
  KEY `Hutang_Detail_ID_JUAL` (`ID_BELI`),
  KEY `Hutang_Detail_ID_USER_BAYAR` (`ID_USER`),
  KEY `idx_id_bayar_hutang` (`ID_BAYAR`),
  KEY `idx_hutang_detail_jenis_beli` (`JENIS`,`ID_BELI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
