CREATE TABLE IF NOT EXISTS `jurnalumum` (
  `NO` int(11) NOT NULL AUTO_INCREMENT,
  `NO_TRANSAKSI` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `TGL_TRANSAKSI` datetime DEFAULT NULL,
  `NO_NOTA` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `URAIAN` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `AKUN_D` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_AKUN_D` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NOMOR_AKUN_D` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `AKUN_K` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_AKUN_K` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NOMOR_AKUN_K` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_BANTU_D` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `KODE_BANTU_D` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_BANTU_K` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `KODE_BANTU_K` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NOMINAL` decimal(20,0) DEFAULT '0',
  `JENIS_TRANSAKSI` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LOKASI` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_USER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_KOMPUTER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `sync_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`NO`),
  UNIQUE KEY `uq_sync_id_jurnalumum` (`sync_id`),
  KEY `idx_no_transaksi_jurnal` (`NO_TRANSAKSI`),
  KEY `idx_tgl_jenis_transaksi` (`TGL_TRANSAKSI`,`JENIS_TRANSAKSI`),
  KEY `idx_nomor_akun_d_jurnal` (`NOMOR_AKUN_D`,`TGL_TRANSAKSI`),
  KEY `idx_nomor_akun_k_jurnal` (`NOMOR_AKUN_K`,`TGL_TRANSAKSI`),
  KEY `idx_covering_akun_d` (`TGL_TRANSAKSI`,`NOMOR_AKUN_D`,`NOMINAL`),
  KEY `idx_covering_akun_k` (`TGL_TRANSAKSI`,`NOMOR_AKUN_K`,`NOMINAL`),
  KEY `idx_tgl_id_user_jurnal` (`TGL_TRANSAKSI`,`ID_USER`),
  KEY `idx_updated_at_jurnal` (`updated_at`),
  KEY `idx_lokasi_jurnal` (`LOKASI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
