CREATE TABLE IF NOT EXISTS `pembelian_detail` (
  `NO` int(11) NOT NULL AUTO_INCREMENT,
  `FAKTUR_BELI` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NOTA_BELI` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TANGGAL_MASUK` datetime DEFAULT NULL,
  `LOKASI` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_SUPLIYER` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_SUPLIYER` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_BARANG` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_BARANG` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `HARGA_BELI` decimal(15,4) NOT NULL DEFAULT '0.0000',
  `HARGA_AVERAGE` decimal(15,4) NOT NULL DEFAULT '0.0000',
  `HARGA_BELI_SEBELUMNYA` decimal(15,4) NOT NULL DEFAULT '0.0000',
  `QTY` decimal(10,2) DEFAULT '0.00',
  `SATUAN` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ISI_SATUAN` int(11) NOT NULL DEFAULT '1',
  `HARGA_BELI_SATUAN` decimal(15,4) NOT NULL DEFAULT '0.0000',
  `QTY_SAT` decimal(10,2) DEFAULT '0.00',
  `TOTAL` decimal(15,0) DEFAULT '0',
  `ID_USER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_KOMPUTER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `sync_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `URUTAN` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`NO`),
  UNIQUE KEY `uq_sync_id_pembelian_detail` (`sync_id`),
  KEY `idx_faktur_beli` (`FAKTUR_BELI`),
  KEY `idx_faktur_beli_barang` (`FAKTUR_BELI`,`ID_BARANG`),
  KEY `idx_tanggal_masuk_beli` (`TANGGAL_MASUK`),
  KEY `idx_tgl_masuk_barang` (`TANGGAL_MASUK`,`ID_BARANG`),
  KEY `idx_id_barang_tgl_masuk` (`ID_BARANG`,`TANGGAL_MASUK`),
  KEY `idx_id_barang_beli` (`ID_BARANG`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
