CREATE TABLE IF NOT EXISTS `pembelian` (
  `ID_PEMBELIAN` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `ID_SUPPLIER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_SUPLIYER` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NOTA_PEMBELIAN` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TGL_BELI` datetime DEFAULT NULL,
  `LOKASI` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JENIS_BAYAR` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `KODE_AKUN_TF` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `NAMA_AKUN_TF` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `GRAND_TOTAL_BELI` decimal(15,0) DEFAULT '0',
  `DISKON_SUPPLIER` decimal(15,2) NOT NULL DEFAULT '0.00',
  `PPN_MASUKAN` decimal(15,2) NOT NULL DEFAULT '0.00',
  `BIAYA_KIRIM` decimal(15,2) NOT NULL DEFAULT '0.00',
  `BIAYA_LAIN` decimal(15,2) NOT NULL DEFAULT '0.00',
  `KODE_AKUN_BIAYA_LAIN` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `NAMA_AKUN_BIAYA_LAIN` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `TOTAL_QTY` decimal(10,2) DEFAULT '0.00',
  `TOTAL_BARANG` decimal(10,2) DEFAULT '0.00',
  `PEMBAYARAN` decimal(15,0) DEFAULT '0',
  `NOMINAL_TRANSFER` decimal(15,2) DEFAULT '0.00',
  `TGL_RETUR` datetime DEFAULT NULL,
  `RETUR` decimal(15,0) DEFAULT '0',
  `TAGIHAN` decimal(15,0) DEFAULT '0',
  `JATUH_TEMPO` datetime DEFAULT NULL,
  `TGL_BAYAR` datetime DEFAULT NULL,
  `NOMINALBAYAR` decimal(15,0) DEFAULT '0',
  `STATUS_JUAL` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `STATUS_TRANSAKSI_BELI` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_USER` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_KOMPUTER` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `sync_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_PEMBELIAN`),
  UNIQUE KEY `uq_sync_id_pembelian` (`sync_id`),
  KEY `idx_tgl_beli` (`TGL_BELI`),
  KEY `idx_supplier_tagihan` (`ID_SUPPLIER`,`TAGIHAN`),
  KEY `idx_id_supplier` (`ID_SUPPLIER`),
  KEY `idx_status_transaksi_beli` (`STATUS_TRANSAKSI_BELI`),
  KEY `idx_jenis_bayar` (`JENIS_BAYAR`),
  KEY `idx_id_user_pembelian` (`ID_USER`),
  KEY `idx_updated_at_beli` (`updated_at`),
  KEY `idx_tgl_jenis_bayar` (`TGL_BELI`,`JENIS_BAYAR`),
  KEY `idx_supplier_status` (`ID_SUPPLIER`,`STATUS_TRANSAKSI_BELI`),
  KEY `idx_jatuh_tempo_status_beli` (`JATUH_TEMPO`,`STATUS_TRANSAKSI_BELI`),
  KEY `idx_tgl_bayar_beli` (`TGL_BAYAR`),
  KEY `idx_status_jual_beli` (`STATUS_JUAL`),
  KEY `idx_status_lokasi_beli` (`STATUS_TRANSAKSI_BELI`,`LOKASI`),
  KEY `idx_tgl_lokasi_beli` (`TGL_BELI`,`LOKASI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
