CREATE TABLE IF NOT EXISTS `penjualan_ditahan_detail` (
  `FAKTUR_JUAL` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_BARANG` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_BARANG` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SERIAL_NUMBER` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `HARGA_BELI` decimal(15,4) NOT NULL DEFAULT '0.0000',
  `QTY` decimal(10,2) DEFAULT '0.00',
  `SATUAN` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ISI_SATUAN` smallint(6) DEFAULT '0',
  `HARGA_BELI_SATUAN` decimal(15,4) NOT NULL DEFAULT '0.0000',
  `HARGA_JUAL` decimal(10,2) DEFAULT '0.00',
  `QTY_SATUAN` decimal(10,2) DEFAULT '0.00',
  `DISKON_PERSEN` decimal(10,2) DEFAULT '0.00',
  `DISKON_RP` decimal(10,2) DEFAULT '0.00',
  `TOTAL_DISKON` decimal(10,2) DEFAULT '0.00',
  `TOTAL_HARGA` decimal(15,0) DEFAULT '0',
  `TOKO` decimal(10,2) DEFAULT '0.00',
  `GUDANG` decimal(10,2) DEFAULT '0.00',
  `STOK` decimal(10,2) DEFAULT '0.00',
  `SISA` decimal(10,2) DEFAULT '0.00',
  `URUTAN` int(11) NOT NULL DEFAULT '0',
  KEY `idx_faktur_jual_ditahan_detail` (`FAKTUR_JUAL`),
  KEY `idx_id_barang_ditahan_detail` (`ID_BARANG`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
