CREATE TABLE IF NOT EXISTS `penjualan_detail` (
  `FAKTUR_JUAL` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_PELANGGAN` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_PELANGGAN` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JENIS_PELANGGAN` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LOKASIBARANG` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TANGGAL_JUAL` datetime DEFAULT NULL,
  `ID_BARANG` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_BARANG` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SERIAL_NUMBER` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `HARGA_BELI` decimal(15,4) NOT NULL DEFAULT '0.0000',
  `QTY` decimal(10,2) DEFAULT '0.00',
  `SATUAN` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ISI_SATUAN` int(11) DEFAULT '0',
  `HARGA_BELI_SATUAN` decimal(15,4) NOT NULL DEFAULT '0.0000',
  `HARGA_JUAL` decimal(15,0) DEFAULT '0',
  `QTY_SATUAN` decimal(10,2) DEFAULT '0.00',
  `DISKON_PERSEN` decimal(10,2) DEFAULT '0.00',
  `DISKON_RP` decimal(10,2) DEFAULT '0.00',
  `TOTAL_DISKON` decimal(10,2) DEFAULT '0.00',
  `TOTAL_HARGA` decimal(15,0) DEFAULT '0',
  `LABA` decimal(10,2) DEFAULT '0.00',
  `ID_USER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_KOMPUTER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `sync_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `URUTAN` int(11) NOT NULL DEFAULT '0',
  UNIQUE KEY `uq_sync_id_penjualan_detail` (`sync_id`),
  KEY `idx_faktur_jual` (`FAKTUR_JUAL`),
  KEY `idx_faktur_barang` (`FAKTUR_JUAL`,`ID_BARANG`),
  KEY `idx_tgl_lokasi_jual` (`TANGGAL_JUAL`,`LOKASIBARANG`),
  KEY `idx_pelanggan_tgl_jual` (`ID_PELANGGAN`,`TANGGAL_JUAL`),
  KEY `idx_id_barang_detail_jual` (`ID_BARANG`),
  KEY `idx_tgl_pelanggan_user` (`TANGGAL_JUAL`,`NAMA_PELANGGAN`,`ID_USER`),
  KEY `idx_barang_faktur` (`ID_BARANG`,`FAKTUR_JUAL`),
  KEY `idx_tgl_lokasi_barang` (`TANGGAL_JUAL`,`LOKASIBARANG`,`ID_BARANG`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
