CREATE TABLE IF NOT EXISTS `penjualan` (
  `ID_PENJUALAN` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `NO_SO` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_PELANGGAN` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_PELANGGAN` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ALAMAT_PELANGGAN` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JENIS_PELANGGAN` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LOKASIBARANG` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TGL_TRANSAKSI` datetime DEFAULT NULL,
  `TOTAL_HPP` decimal(15,2) DEFAULT '0.00',
  `GRAND_TOTAL_SBL_PAJAK` decimal(15,2) DEFAULT '0.00',
  `DISKON_TOTAL_PERSEN` decimal(10,2) DEFAULT '0.00',
  `DISKON_TOTAL_RP` decimal(10,2) DEFAULT '0.00',
  `PAJAK_PERSEN` decimal(10,2) DEFAULT '0.00',
  `PAJAK_RP` decimal(10,2) DEFAULT '0.00',
  `GRAND_TOTAL_STL_PAJAK` decimal(15,2) DEFAULT '0.00',
  `LABA` decimal(10,2) DEFAULT '0.00',
  `BAYAR` decimal(15,2) DEFAULT '0.00',
  `NOMINAL_TRANSFER` decimal(15,2) DEFAULT '0.00',
  `BIAYA_KIRIM` decimal(10,2) DEFAULT '0.00',
  `KEMBALI` decimal(15,2) DEFAULT '0.00',
  `TGL_RETUR` datetime DEFAULT NULL,
  `NILAI_RETUR` decimal(10,2) DEFAULT '0.00',
  `TGL_PEMBAYARAN` datetime DEFAULT NULL,
  `NOMINALBAYARPIUTANG` decimal(15,2) DEFAULT '0.00',
  `SISA_TAGIHAN` decimal(15,2) DEFAULT '0.00',
  `JATUH_TEMPO` datetime DEFAULT NULL,
  `STATUS_BAYAR` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `STATUS_TRANSAKSI` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TYPE_AKUN` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `KODE_AKUN` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JENIS_PEMBAYARAN` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `KODE_AKUN_TF` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `NAMA_AKUN_TF` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `TYPE_AKUNBANK` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `KODE_AKUNBANK` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JENIS_PEMBAYARANBANK` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `METODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BANK` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NO_REKENING` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_REKENING` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NO_REFFERENSI` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_SALES` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_SALES` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_USER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_KOMPUTER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `sync_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_PENJUALAN`),
  UNIQUE KEY `uq_sync_id_penjualan` (`sync_id`),
  KEY `idx_tgl_transaksi` (`TGL_TRANSAKSI`),
  KEY `idx_pelanggan_tagihan` (`ID_PELANGGAN`,`SISA_TAGIHAN`),
  KEY `idx_id_pelanggan` (`ID_PELANGGAN`),
  KEY `idx_status_transaksi` (`STATUS_TRANSAKSI`),
  KEY `idx_lokasibarang` (`LOKASIBARANG`),
  KEY `idx_id_user_penjualan` (`ID_USER`),
  KEY `idx_updated_at_jual` (`updated_at`),
  KEY `idx_tgl_kode_akun_jual` (`TGL_TRANSAKSI`,`KODE_AKUN`),
  KEY `idx_tgl_kode_akun_tf` (`TGL_TRANSAKSI`,`KODE_AKUN_TF`),
  KEY `idx_pelanggan_status` (`ID_PELANGGAN`,`STATUS_TRANSAKSI`),
  KEY `idx_lokasi_tanggal` (`LOKASIBARANG`,`TGL_TRANSAKSI`),
  KEY `idx_pelanggan_tgl_jual` (`ID_PELANGGAN`,`TGL_TRANSAKSI`),
  KEY `idx_lokasi_tgl_pelanggan` (`LOKASIBARANG`,`TGL_TRANSAKSI`,`ID_PELANGGAN`),
  KEY `idx_jatuh_tempo_status_jual` (`JATUH_TEMPO`,`STATUS_TRANSAKSI`),
  KEY `idx_id_sales_tgl_jual` (`ID_SALES`,`TGL_TRANSAKSI`),
  KEY `idx_type_akun_jual` (`TYPE_AKUN`),
  KEY `idx_tgl_type_akun_jual` (`TGL_TRANSAKSI`,`TYPE_AKUN`),
  KEY `idx_id_tgl_lokasi` (`ID_PENJUALAN`,`TGL_TRANSAKSI`,`LOKASIBARANG`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
