CREATE TABLE IF NOT EXISTS `retur_pembelian` (
  `ID_RETUR_PEMBELIAN` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TGL_RETUR_BELI` datetime DEFAULT NULL,
  `ID_SUPPLIER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_SUPPLIER` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ALAMAT_SUPPLIER` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `KONTAK_SUPPLIER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_PEMBELIAN` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TGL_PEMBELIAN` datetime DEFAULT NULL,
  `STATUS_PEMBELIAN` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PENYIMPANAN` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BAYAR_PEMBELIAN` decimal(15,0) DEFAULT '0',
  `SISA_PEMBELIAN` decimal(15,0) DEFAULT NULL,
  `TOTAL_BARANG` int(11) DEFAULT '0',
  `TOTAL_QTY` decimal(10,2) DEFAULT '0.00',
  `TOTAL_RUPIAH` decimal(15,0) DEFAULT '0',
  `JENIS_PENGEMBALIAN` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_REKENING` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `KODE_REKENING` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_REKENING_TRANSFER` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Nama akun untuk pembayaran transfer',
  `KODE_REKENING_TRANSFER` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Kode akun untuk pembayaran transfer',
  `NOMINAL_TUNAI` decimal(15,2) DEFAULT '0.00' COMMENT 'Nominal pembayaran tunai',
  `NOMINAL_TRANSFER` decimal(15,2) DEFAULT '0.00' COMMENT 'Nominal pembayaran transfer',
  `ALASAN_RETUR` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_USER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_KOMPUTER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `sync_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  UNIQUE KEY `uq_sync_id_retur_pembelian` (`sync_id`),
  KEY `retur_pembelian_ID_KOMPUTER` (`ID_KOMPUTER`),
  KEY `retur_pembelian_ID_PEMBELIAN` (`ID_PEMBELIAN`),
  KEY `retur_pembelian_ID_RETUR_PEMBELIAN` (`ID_RETUR_PEMBELIAN`),
  KEY `retur_pembelian_ID_SUPPLIER` (`ID_SUPPLIER`),
  KEY `idx_tgl_retur_beli` (`TGL_RETUR_BELI`),
  KEY `idx_kode_rekening_retur_beli` (`KODE_REKENING`),
  KEY `idx_id_user_retur_beli` (`ID_USER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
