CREATE TABLE IF NOT EXISTS `retur_penjualan_detail` (
  `ID_RETUR_PENJUALAN` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TGL_RETUR_JUAL` datetime DEFAULT NULL,
  `LOKASI` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_PELANGGAN` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_PELANGGAN` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JENIS_PELANGGAN` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_BARANG` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_BARANG` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `HARGA_BELI` decimal(15,4) NOT NULL DEFAULT '0.0000',
  `QTY` decimal(10,2) DEFAULT '0.00',
  `SATUAN` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ISI_SATUAN` int(11) NOT NULL DEFAULT '1',
  `QTY_SATUAN` decimal(10,2) DEFAULT '0.00',
  `HARGA_BELI_SATUAN` decimal(15,4) NOT NULL DEFAULT '0.0000',
  `HARGA_JUAL` decimal(10,2) DEFAULT '0.00',
  `TOTAL_DISKON` decimal(10,2) DEFAULT '0.00',
  `TOTAL_HARGA` decimal(15,0) DEFAULT '0',
  `LABA` decimal(10,2) DEFAULT '0.00',
  `ID_USER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_KOMPUTER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `sync_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `URUTAN` int(11) NOT NULL DEFAULT '0',
  UNIQUE KEY `uq_sync_id_retur_penjualan_detail` (`sync_id`),
  KEY `idx_id_retur_penjualan` (`ID_RETUR_PENJUALAN`),
  KEY `idx_retur_jual_barang` (`ID_RETUR_PENJUALAN`,`ID_BARANG`),
  KEY `idx_tgl_retur_jual_detail` (`TGL_RETUR_JUAL`),
  KEY `idx_tgl_pelanggan_retur_jual` (`TGL_RETUR_JUAL`,`NAMA_PELANGGAN`),
  KEY `idx_lokasi_retur_jual_detail` (`LOKASI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
