CREATE TABLE IF NOT EXISTS `retur_pembelian_detail` (
  `ID_RETUR_PEMBELIAN` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TGL_RETUR_BELI` datetime DEFAULT NULL,
  `ID_SUPLIYER` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_SUPLIYER` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_BARANG` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_BARANG` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `HARGA_BELI` decimal(15,4) NOT NULL DEFAULT '0.0000',
  `QTY` decimal(10,2) DEFAULT '0.00',
  `SATUAN` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ISI_SATUAN` int(11) DEFAULT '0',
  `HARGA_BELI_SATUAN` decimal(15,4) NOT NULL DEFAULT '0.0000',
  `QTY_SAT` decimal(10,2) DEFAULT '0.00',
  `TOTAL` decimal(15,0) DEFAULT '0',
  `PENYIMPANAN` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_USER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_KOMPUTER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `sync_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `URUTAN` int(11) NOT NULL DEFAULT '0',
  UNIQUE KEY `uq_sync_id_retur_pembelian_detail` (`sync_id`),
  KEY `idx_id_retur_pembelian` (`ID_RETUR_PEMBELIAN`),
  KEY `idx_tgl_retur_beli_detail` (`TGL_RETUR_BELI`),
  KEY `idx_tgl_supplier_retur_beli` (`TGL_RETUR_BELI`,`NAMA_SUPLIYER`),
  KEY `idx_penyimpanan_retur_beli_detail` (`PENYIMPANAN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
