CREATE TABLE IF NOT EXISTS `stok_opname` (
  `ID_STOK_OPNAME` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TANGGAL` datetime DEFAULT NULL,
  `LOKASI` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_BARANG` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_BARANG` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `KATEGORI` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `HARGA` decimal(10,2) DEFAULT '0.00',
  `STOK_SYSTEM` decimal(10,2) DEFAULT '0.00',
  `STOK_NYATA` decimal(10,2) DEFAULT '0.00',
  `STOK_SELISIH` decimal(10,2) DEFAULT '0.00',
  `SATUAN` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ISI_SATUAN` smallint(6) DEFAULT '0',
  `TOTAL_QTY` decimal(10,2) DEFAULT '0.00',
  `TOTAL_HARGA` decimal(15,0) DEFAULT '0',
  `KETERANGAN` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_USER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_KOMPUTER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `sync_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `URUTAN` int(11) NOT NULL DEFAULT '0',
  UNIQUE KEY `uq_sync_id_stok_opname` (`sync_id`),
  KEY `idx_tanggal_opname` (`TANGGAL`),
  KEY `idx_id_stok_opname` (`ID_STOK_OPNAME`),
  KEY `idx_id_barang_opname` (`ID_BARANG`),
  KEY `idx_barang_tanggal` (`ID_BARANG`,`TANGGAL`),
  KEY `idx_tanggal_lokasi_opname` (`TANGGAL`,`LOKASI`),
  KEY `idx_lokasi_tanggal_opname` (`LOKASI`,`TANGGAL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
