CREATE TABLE IF NOT EXISTS `tbl_supliyer` (
  `KODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `NAMA` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ALAMAT` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `HP` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JANGKAHUTANG` int(11) DEFAULT '0',
  `HUTANGAWAL` decimal(15,0) DEFAULT '0',
  `TOTALHUTANG` decimal(15,0) DEFAULT '0',
  `TOTALBAYAR` decimal(15,0) DEFAULT '0',
  `HUTANGAKHIR` decimal(15,0) DEFAULT '0',
  `Status` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Aktif',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `sync_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_cloud` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_by` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_dirty` tinyint(4) NOT NULL DEFAULT '1',
  `version` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`KODE`),
  UNIQUE KEY `uq_sync_id_tbl_supliyer` (`sync_id`),
  KEY `idx_nama_supliyer` (`NAMA`),
  KEY `idx_status_nama` (`Status`,`NAMA`),
  KEY `idx_updated_at_supliyer` (`updated_at`),
  KEY `idx_is_dirty` (`is_dirty`),
  KEY `idx_id_cloud` (`id_cloud`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
