CREATE TABLE IF NOT EXISTS `tbl_datareferensi` (
  `STATUS` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Terkunci = tidak bisa dihapus user | NULL = bebas dihapus',
  `JENIS_AKUN` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Filter laporan: ASET LANCAR | ASET TETAP | PASIVA | MODAL | PENJUALAN | HPP | BIAYA | PENDAPATAN LAIN | PAJAK',
  `TYPE_AKUN` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Prefix urutan kode akun, dipakai filter dropdown FormTabelReferensi',
  `KODE_AKUN` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Primary key format XX.XX.XXX',
  `NAMA_AKUN` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Nama lengkap akun',
  `SUB_AKUN` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'AKTIVA | PASIVA | LABA RUGI | LABA (pendapatan+kontra-beban) | RUGI (beban+kontra-pendapatan)',
  `AKUN_DK` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Saldo normal: DEBET | KREDIT',
  `AKUN_NRLR` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Posisi di laporan: NERACA | LABA RUGI',
  `KETERANGAN` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'Penjelasan akuntansi lengkap fungsi akun',
  `SALDO_AWAL` decimal(20,0) DEFAULT '0' COMMENT 'Saldo awal periode (titik awal kalkulasi, tidak pernah diubah oleh laporan)',
  `SALDO_SEBELUMNYA` decimal(20,0) DEFAULT '0' COMMENT 'Kolom warisan (legacy) ΓÇö nilainya selalu = SALDO_AWAL setelah posting resmi. Kalkulasi periode pakai temp_datareferensi',
  `S_DEBET` decimal(20,0) DEFAULT '0' COMMENT 'Total mutasi debet periode ini dari JurnalUmum',
  `S_KREDIT` decimal(20,0) DEFAULT '0' COMMENT 'Total mutasi kredit periode ini dari JurnalUmum',
  `SALDO_AKHIR` decimal(20,0) DEFAULT '0' COMMENT 'Saldo akhir = SALDO_SEBELUMNYA +/- mutasi sesuai AKUN_DK',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `sync_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`KODE_AKUN`),
  UNIQUE KEY `uq_sync_id_tbl_datareferensi` (`sync_id`),
  KEY `idx_nama_akun` (`NAMA_AKUN`),
  KEY `idx_type_akun` (`TYPE_AKUN`),
  KEY `idx_kode_akun_ref` (`KODE_AKUN`),
  KEY `idx_sub_akun` (`SUB_AKUN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
