CREATE TABLE IF NOT EXISTS `tbl_pelanggan` (
  `KODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `NAMA` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ALAMAT` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NO_TELP` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JENIS` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JANGKAPIUTANG` smallint(6) DEFAULT '0',
  `HUTANGAWAL` decimal(15,0) DEFAULT '0',
  `TOTALHUTANG` decimal(15,0) DEFAULT '0',
  `TOTALBAYAR` decimal(15,0) DEFAULT '0',
  `HUTANGAKHIR` decimal(15,0) DEFAULT '0',
  `SALDO_POIN` int(11) NOT NULL DEFAULT '0' COMMENT 'Saldo poin loyalitas terkini',
  `Status` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Aktif',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `sync_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_cloud` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_by` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_dirty` tinyint(4) NOT NULL DEFAULT '1',
  `version` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`KODE`),
  UNIQUE KEY `uq_sync_id_tbl_pelanggan` (`sync_id`),
  KEY `idx_nama_pelanggan` (`NAMA`),
  KEY `idx_updated_at_pelanggan` (`updated_at`),
  KEY `idx_is_dirty` (`is_dirty`),
  KEY `idx_id_cloud` (`id_cloud`),
  KEY `idx_status_pelanggan` (`Status`),
  KEY `idx_status_nama_pelanggan` (`Status`,`NAMA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
