CREATE TABLE IF NOT EXISTS `tbl_barang` (
  `ID_BARANG` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `ID_BARANG_BANTU` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_BARANG` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `NAMA_BARANG_BANTU` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JENIS` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `KODE_KATEGORI` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_KATEGORI` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `KODE_SUPLIYER` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_SUPLIYER` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `KODE_MERK` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_MERK` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SERIAL_NUMBER` tinyint(1) DEFAULT NULL,
  `JENIS_SATUAN` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `HARGA_BELI` decimal(15,4) NOT NULL DEFAULT '0.0000',
  `HARGA_BELI_TERAKHIR` decimal(15,4) NOT NULL DEFAULT '0.0000',
  `HPP_UMUM_KECIL` decimal(10,2) DEFAULT '0.00',
  `HPP_UMUM_SEDANG` decimal(10,2) DEFAULT '0.00',
  `HPP_UMUM_BESAR` decimal(10,2) DEFAULT '0.00',
  `HARGA_BELI_UMUM_KECIL` decimal(10,2) DEFAULT '0.00',
  `HARGA_BELI_UMUM_SEDANG` decimal(10,2) DEFAULT '0.00',
  `HARGA_BELI_UMUM_BESAR` decimal(10,2) DEFAULT '0.00',
  `HPP_PARTAI_KECIL` decimal(10,2) DEFAULT '0.00',
  `HPP_PARTAI_SEDANG` decimal(10,2) DEFAULT '0.00',
  `HPP_PARTAI_BESAR` decimal(10,2) DEFAULT '0.00',
  `HARGA_BELI_PARTAI_KECIL` decimal(10,2) DEFAULT '0.00',
  `HARGA_BELI_UPARTAI_SEDANG` decimal(10,2) DEFAULT '0.00',
  `HARGA_BELI_PARTAI_BESAR` decimal(10,2) DEFAULT '0.00',
  `BARCODE_KECIL` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BARCODE_SEDANG` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BARCODE_BESAR` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SATUAN_UMUM_KECIL` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SATUAN_UMUM_SEDANG` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SATUAN_UMUM_BESAR` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ISI_UMUM_KECIL` int(11) DEFAULT '0',
  `ISI_UMUM_SEDANG` int(11) DEFAULT '0',
  `ISI_UMUM_BESAR` int(11) DEFAULT '0',
  `HARGA_JUAL_UMUM_KECIL` decimal(10,2) DEFAULT '0.00',
  `HARGA_JUAL_UMUM_SEDANG` decimal(10,2) DEFAULT '0.00',
  `HARGA_JUAL_UMUM_BESAR` decimal(10,2) DEFAULT '0.00',
  `SATUAN_PARTAI_KECIL` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SATUAN_PARTAI_SEDANG` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SATUAN_PARTAI_BESAR` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ISI_PARTAI_KECIL` int(11) DEFAULT '0',
  `ISI_PARTAI_SEDANG` int(11) DEFAULT '0',
  `ISI_PARTAI_BESAR` int(11) DEFAULT '0',
  `HARGA_JUAL_PARTAI_KECIL` decimal(10,2) DEFAULT '0.00',
  `HARGA_JUAL_PARTAI_SEDANG` decimal(10,2) DEFAULT '0.00',
  `HARGA_JUAL_PARTAI_BESAR` decimal(10,2) DEFAULT '0.00',
  `AWAL_TOKO` decimal(10,2) DEFAULT '0.00',
  `STOK_AWAL_TOKO` decimal(10,2) DEFAULT '0.00',
  `TAMBAH_TOKO` decimal(10,2) DEFAULT '0.00',
  `KURANG_TOKO` decimal(10,2) DEFAULT '0.00',
  `PEMBELIAN_TOKO` decimal(10,2) DEFAULT '0.00',
  `PENJUALAN_TOKO` decimal(10,2) DEFAULT '0.00',
  `RETUR_BELI_TOKO` decimal(10,2) DEFAULT '0.00',
  `RETUR_JUAL_TOKO` decimal(10,2) DEFAULT '0.00',
  `OPNAME_TOKO` decimal(10,2) DEFAULT '0.00',
  `TRANSFER_STOK_MASUK_TOKO` decimal(10,2) DEFAULT '0.00',
  `TRANSFER_STOK_KELUAR_TOKO` decimal(10,2) DEFAULT '0.00',
  `TRANSFER_BARANG_MASUK_TOKO` decimal(10,2) DEFAULT '0.00',
  `TRANSFER_BARANG_KELUAR_TOKO` decimal(10,2) DEFAULT '0.00',
  `TRANSFER_CABANG_MASUK_TOKO` decimal(10,2) DEFAULT '0.00',
  `TRANSFER_CABANG_KELUAR_TOKO` decimal(10,2) DEFAULT '0.00',
  `STOK_TOKO` decimal(10,2) DEFAULT '0.00',
  `AWAL_GUDANG` decimal(10,2) DEFAULT '0.00',
  `STOK_AWAL_GUDANG` decimal(10,2) DEFAULT '0.00',
  `TAMBAH_GUDANG` decimal(10,2) DEFAULT '0.00',
  `KURANG_GUDANG` decimal(10,2) DEFAULT '0.00',
  `PEMBELIAN_GUDANG` decimal(10,2) DEFAULT '0.00',
  `PENJUALAN_GUDANG` decimal(10,2) DEFAULT '0.00',
  `RETUR_BELI_GUDANG` decimal(10,2) DEFAULT '0.00',
  `RETUR_JUAL_GUDANG` decimal(10,2) DEFAULT '0.00',
  `OPNAME_GUDANG` decimal(10,2) DEFAULT '0.00',
  `TRANSFER_STOK_MASUK_GUDANG` decimal(10,2) DEFAULT '0.00',
  `TRANSFER_STOK_KELUAR_GUDANG` decimal(10,2) DEFAULT '0.00',
  `TRANSFER_BARANG_MASUK_GUDANG` decimal(10,2) DEFAULT '0.00',
  `TRANSFER_BARANG_KELUAR_GUDANG` decimal(10,2) DEFAULT '0.00',
  `TRANSFER_CABANG_MASUK_GUDANG` decimal(10,2) DEFAULT '0.00',
  `TRANSFER_CABANG_KELUAR_GUDANG` decimal(10,2) DEFAULT '0.00',
  `STOK_GUDANG` decimal(10,2) DEFAULT '0.00',
  `SATUAN_STOK` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SATUAN_ISI_STOK` int(11) DEFAULT '0',
  `STOK_MIN` decimal(10,2) DEFAULT '0.00',
  `STOK_MAX` decimal(10,2) DEFAULT '0.00',
  `LOKASI_RAK_TOKO` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LOKASI_RAK_GUDANG` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `POINT_MEMBER` decimal(10,2) DEFAULT '0.00',
  `POINT_KARYAWAN` decimal(10,2) DEFAULT '0.00',
  `KOMISI_SALES_RP` decimal(10,2) DEFAULT '0.00',
  `KOMISI_SALES_PERSEN` decimal(10,2) DEFAULT '0.00',
  `STATUS` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Aktif',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `sync_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_cloud` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_by` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_dirty` tinyint(4) NOT NULL DEFAULT '1',
  `version` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID_BARANG`),
  UNIQUE KEY `uq_sync_id_tbl_barang` (`sync_id`),
  KEY `idx_nama_barang` (`NAMA_BARANG`),
  KEY `idx_barcode_kecil` (`BARCODE_KECIL`),
  KEY `idx_barcode_sedang` (`BARCODE_SEDANG`),
  KEY `idx_barcode_besar` (`BARCODE_BESAR`),
  KEY `idx_updated_at_barang` (`updated_at`),
  KEY `idx_is_dirty` (`is_dirty`),
  KEY `idx_id_cloud` (`id_cloud`),
  KEY `idx_stok_minimum` (`STOK_MIN`,`STOK_TOKO`,`STOK_GUDANG`),
  KEY `idx_kategori_barang` (`NAMA_KATEGORI`),
  KEY `idx_kode_kategori_barang` (`KODE_KATEGORI`),
  KEY `idx_status_barang` (`STATUS`),
  KEY `idx_status_nama_barang` (`STATUS`,`NAMA_BARANG`),
  KEY `idx_stok_toko_id_nama_harga` (`STOK_TOKO`,`ID_BARANG`,`NAMA_BARANG`,`HARGA_BELI`),
  KEY `idx_stok_gudang_id_nama_harga` (`STOK_GUDANG`,`ID_BARANG`,`NAMA_BARANG`,`HARGA_BELI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
