CREATE TABLE IF NOT EXISTS `tbl_gaji` (
  `KODE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `HARI_KERJA` smallint(6) DEFAULT '0',
  `PROSENTASE_KOMISI` decimal(10,2) DEFAULT '0.00',
  `BONUS_SUPIR` decimal(10,2) DEFAULT '0.00',
  `BONUS_HELPER` decimal(10,2) DEFAULT '0.00',
  `BONUS_TRANSPORT` decimal(10,2) DEFAULT '0.00',
  `BONUS_MAKAN` decimal(10,2) DEFAULT '0.00',
  `BONUS_LEMBUR` decimal(10,2) DEFAULT '0.00',
  `JENIS_POTONGAN` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `POTONGAN_ABSEN` decimal(10,2) DEFAULT '0.00',
  `POTONGAN_ABSEN_KHUSUS` decimal(10,2) DEFAULT '0.00',
  `POTONGAN_TERLAMBAT` decimal(10,2) DEFAULT '0.00',
  PRIMARY KEY (`KODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
