CREATE TABLE IF NOT EXISTS `transfer_stok` (
  `ID_TRANSFER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JENIS_TRANSFER` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `URAIAN` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TANGGAL` datetime DEFAULT NULL,
  `ID_BARANG_M` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_BARANG_M` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `QTY_M` decimal(10,2) DEFAULT '0.00',
  `SATUAN_M` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ISI_M` decimal(10,2) DEFAULT '0.00',
  `QTY_SAT_M` decimal(10,2) DEFAULT '0.00',
  `HARGA_SAT_M` decimal(10,2) DEFAULT '0.00',
  `TOTAL_HARGA_M` decimal(15,0) DEFAULT '0',
  `ID_BARANG_K` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_BARANG_K` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `QTY_K` decimal(10,2) DEFAULT '0.00',
  `SATUAN_K` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ISI_K` decimal(10,2) DEFAULT '0.00',
  `QTY_SAT_K` decimal(10,2) DEFAULT '0.00',
  `HARGA_SAT_K` decimal(10,2) DEFAULT '0.00',
  `TOTAL_HARGA_K` decimal(15,0) DEFAULT '0',
  `Selisih` decimal(10,2) DEFAULT '0.00',
  `ID_USER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_KOMPUTER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `sync_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  UNIQUE KEY `uq_sync_id_transfer_stok` (`sync_id`),
  KEY `idx_tanggal_transfer_stok` (`TANGGAL`),
  KEY `idx_id_transfer_stok` (`ID_TRANSFER`),
  KEY `idx_jenis_transfer` (`JENIS_TRANSFER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
