CREATE TABLE IF NOT EXISTS `transfer_cabang_detail` (
  `ID_TRANSFER` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `TGL_TRANSFER` datetime DEFAULT NULL,
  `LOKASI` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LOKASI_ASAL` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_BARANG` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `NAMA_BARANG` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `HARGA` decimal(15,2) DEFAULT '0.00',
  `QTY` decimal(10,2) DEFAULT '0.00',
  `SATUAN` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ISI_SATUAN` int(11) NOT NULL DEFAULT '1',
  `HARGA_QTY` decimal(15,2) DEFAULT '0.00',
  `TOTAL_QTY` decimal(10,2) DEFAULT '0.00',
  `DITERIMA_QTY` decimal(10,2) DEFAULT '0.00',
  `STATUS_ITEM` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING',
  `TOTAL` decimal(15,2) DEFAULT '0.00',
  `ID_USER` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_KOMPUTER` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `sync_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `URUTAN` int(11) NOT NULL DEFAULT '0',
  UNIQUE KEY `uq_sync_id_transfer_cabang_detail` (`sync_id`),
  KEY `idx_id_transfer_cabang_detail` (`ID_TRANSFER`),
  KEY `idx_id_barang_transfer_cabang` (`ID_BARANG`),
  KEY `idx_transfer_cabang_id_barang` (`ID_TRANSFER`,`ID_BARANG`),
  KEY `idx_tgl_transfer_cabang_detail` (`TGL_TRANSFER`),
  KEY `idx_status_item_transfer_cabang` (`STATUS_ITEM`),
  KEY `idx_lokasi_transfer_cabang_detail` (`LOKASI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
