CREATE TABLE IF NOT EXISTS `transfer_barang_detail` (
  `ID_TRANSFER` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TGL_TRANSFER` datetime DEFAULT NULL,
  `LOKASI` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_BARANG` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAMA_BARANG` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `HARGA` decimal(10,2) DEFAULT '0.00',
  `QTY` decimal(10,2) DEFAULT '0.00',
  `SATUAN` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ISI_SATUAN` int(11) NOT NULL DEFAULT '1',
  `HARGA_QTY` decimal(15,0) DEFAULT '0',
  `TOTAL_QTY` decimal(10,2) DEFAULT '0.00',
  `TOTAL` decimal(15,0) DEFAULT '0',
  `ID_USER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_KOMPUTER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `sync_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `URUTAN` int(11) NOT NULL DEFAULT '0',
  UNIQUE KEY `uq_sync_id_transfer_barang_detail` (`sync_id`),
  KEY `idx_id_transfer_barang_detail` (`ID_TRANSFER`),
  KEY `idx_id_barang_transfer` (`ID_BARANG`),
  KEY `idx_transfer_barang_id` (`ID_TRANSFER`,`ID_BARANG`),
  KEY `idx_tgl_transfer_detail` (`TGL_TRANSFER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
