CREATE TABLE IF NOT EXISTS `transfer_cabang` (
  `ID_TRANSFER` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `TGL_TRANSFER` datetime DEFAULT NULL,
  `LOKASI` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LOKASI_ASAL` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DARI_CABANG` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `KE_CABANG` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `MODE_KIRIM` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'OFFLINE_EXPORT',
  `STATUS_TRANSFER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING',
  `ID_CLOUD_TRANSFER` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FILE_MANUAL` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TOTAL_QTY` decimal(10,2) DEFAULT '0.00',
  `TOTAL_BARANG` int(11) DEFAULT '0',
  `TOTAL_RUPIAH` decimal(15,2) DEFAULT '0.00',
  `ID_USER` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_KOMPUTER` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `sync_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID_TRANSFER`),
  UNIQUE KEY `uq_sync_id_transfer_cabang` (`sync_id`),
  KEY `idx_tgl_transfer_cabang` (`TGL_TRANSFER`),
  KEY `idx_status_transfer_cabang` (`STATUS_TRANSFER`),
  KEY `idx_mode_kirim_cabang` (`MODE_KIRIM`),
  KEY `idx_dari_ke_cabang` (`DARI_CABANG`,`KE_CABANG`),
  KEY `idx_ke_status_cabang` (`KE_CABANG`,`STATUS_TRANSFER`),
  KEY `idx_cloud_transfer_cabang` (`ID_CLOUD_TRANSFER`),
  KEY `idx_lokasi_transfer_cabang` (`LOKASI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
