-- ============================================================
-- Table: penjualan
-- Alter table penjualan: 33 kolom berubah
-- Generated: 2026-08-07 17:33:20
-- ============================================================

-- penjualan: 33 kolom berubah
ALTER TABLE `penjualan`    MODIFY COLUMN `NO_SO` varchar(30) DEFAULT 'NULL',
    MODIFY COLUMN `ID_PELANGGAN` varchar(10) DEFAULT 'NULL',
    MODIFY COLUMN `NAMA_PELANGGAN` varchar(60) DEFAULT 'NULL',
    MODIFY COLUMN `ALAMAT_PELANGGAN` varchar(60) DEFAULT 'NULL',
    MODIFY COLUMN `JENIS_PELANGGAN` varchar(30) DEFAULT 'NULL',
    MODIFY COLUMN `LOKASIBARANG` varchar(20) DEFAULT 'NULL',
    MODIFY COLUMN `TGL_TRANSAKSI` datetime DEFAULT 'NULL',
    MODIFY COLUMN `DISKON_TOTAL_RP` decimal(10,2) DEFAULT '0.00',
    MODIFY COLUMN `PAJAK_RP` decimal(10,2) DEFAULT '0.00',
    MODIFY COLUMN `LABA` decimal(10,2) DEFAULT '0.00',
    MODIFY COLUMN `BIAYA_KIRIM` decimal(10,2) DEFAULT '0.00',
    MODIFY COLUMN `TGL_RETUR` datetime DEFAULT 'NULL',
    MODIFY COLUMN `NILAI_RETUR` decimal(10,2) DEFAULT '0.00',
    MODIFY COLUMN `TGL_PEMBAYARAN` datetime DEFAULT 'NULL',
    MODIFY COLUMN `JATUH_TEMPO` datetime DEFAULT 'NULL',
    MODIFY COLUMN `STATUS_BAYAR` varchar(20) DEFAULT 'NULL',
    MODIFY COLUMN `STATUS_TRANSAKSI` varchar(20) DEFAULT 'NULL',
    MODIFY COLUMN `TYPE_AKUN` varchar(20) DEFAULT 'NULL',
    MODIFY COLUMN `KODE_AKUN` varchar(50) DEFAULT 'NULL',
    MODIFY COLUMN `JENIS_PEMBAYARAN` varchar(50) DEFAULT 'NULL',
    MODIFY COLUMN `TYPE_AKUNBANK` varchar(20) DEFAULT 'NULL',
    MODIFY COLUMN `KODE_AKUNBANK` varchar(50) DEFAULT 'NULL',
    MODIFY COLUMN `JENIS_PEMBAYARANBANK` varchar(50) DEFAULT 'NULL',
    MODIFY COLUMN `METODE` varchar(20) DEFAULT 'NULL',
    MODIFY COLUMN `BANK` varchar(50) DEFAULT 'NULL',
    MODIFY COLUMN `NO_REKENING` varchar(30) DEFAULT 'NULL',
    MODIFY COLUMN `NAMA_REKENING` varchar(50) DEFAULT 'NULL',
    MODIFY COLUMN `NO_REFFERENSI` varchar(100) DEFAULT 'NULL',
    MODIFY COLUMN `ID_SALES` varchar(20) DEFAULT 'NULL',
    MODIFY COLUMN `NAMA_SALES` varchar(100) DEFAULT 'NULL',
    MODIFY COLUMN `ID_USER` varchar(20) DEFAULT 'NULL',
    MODIFY COLUMN `ID_KOMPUTER` varchar(20) DEFAULT 'NULL',
    MODIFY COLUMN `sync_id` varchar(36) DEFAULT 'NULL';

