PrinterPos=Microsoft Print to PDF
PortPrinter=
Maju=0
Mundur=0
Lebar=75
Piksel=100
BatasKiri=0
Jarak=2
Potongkertas=True
ModelStruk=Model 4 Lengkap Tanpa Logo
FontNama=Century
FontKet=Arial Narrow
FontIsi=Arial Narrow
FOntFoot=Arial Narrow
FontUNama=14
FontUKet=10
FontUIsi=10
FontUFoot=10
PortName=Microsoft Print to PDF
BaudRate=9600
Parity=None
DataBits=8
PortCashDraw=COM1
CodeCashDraw=OPTION 2
StatusComp=Server
JenisPrinterJual=Printer Thermal
Panjang=10
JenisPrinterLap=Printer Dot Matrix

PrinterDot=Microsoft Print to PDF
LebarDot=27
BatasKiriDot=2
JarakBarisDot=5
FontJudulDot=Consolas
FontIsiDot=Consolas
UkuranFontJudul=12
UkuranFontIsi=9
TinggiDot=10
