DROP PROCEDURE IF EXISTS `sp_bat_stok_toko`;
DELIMITER //
sp_bat_stok_toko

CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_bat_stok_toko`()
BEGIN
    UPDATE tbl_barang SET
        STOK_TOKO = COALESCE(AWAL_TOKO, 0)
            + COALESCE(TAMBAH_TOKO, 0)              - COALESCE(KURANG_TOKO, 0)
            + COALESCE(PEMBELIAN_TOKO, 0)           - COALESCE(PENJUALAN_TOKO, 0)
            - COALESCE(RETUR_BELI_TOKO, 0)          + COALESCE(RETUR_JUAL_TOKO, 0)
            + COALESCE(OPNAME_TOKO, 0)
            + COALESCE(TRANSFER_STOK_MASUK_TOKO, 0)    - COALESCE(TRANSFER_STOK_KELUAR_TOKO, 0)
            + COALESCE(TRANSFER_BARANG_MASUK_TOKO, 0)  - COALESCE(TRANSFER_BARANG_KELUAR_TOKO, 0)
            + COALESCE(TRANSFER_CABANG_MASUK_TOKO, 0)  - COALESCE(TRANSFER_CABANG_KELUAR_TOKO, 0);
END
utf8mb4
utf8mb4_0900_ai_ci
utf8mb4_unicode_ci
//
DELIMITER ;
